/**
 * Options for constructing a {@link Controller} instance.
 */
export interface ControllerOptions {
  /** The callback URL for receiving payment notifications. */
  callbackHost: string;
  /** Your MTN Momo user API key. */
  userApiKey: string;
  /** Your MTN Momo API user ID. */
  userId: string;
  /** Your MTN Momo primary key. */
  primaryKey: string;
}

/**
 * Options for the {@link makeRequest} function.
 */
export interface MakeRequestOptions extends ControllerOptions {
  /** The amount to be paid. */
  amount: string | number;
  /** The currency of the payment. */
  currency: string;
  /** An ID generated by your system to uniquely identify the transaction. */
  externalId: string;
  /** The type of the party ID (e.g., MSISDN, EMAIL, etc.). */
  partyIdType: string;
  /** The party ID of the payer. */
  partyId: string;
  /** A message that will be displayed to the payer. */
  payerMessage: string;
  /** A note that will be displayed to the payee. */
  payeeNote: string;
}

/**
 * The response returned by {@link Controller.requestToPay}.
 */
export interface RequestToPayResponse {
  /** The response code from the API. */
  responseCode: string | number;
  /** The reference ID generated for the transaction. */
  referenceId: string;
}

/**
 * The resolved value of {@link makeRequest}.
 */
export interface MakeRequestResult {
  /** The response from the API. */
  response: RequestToPayResponse;
  /** The transaction status. */
  status: Record<string, unknown>;
}

/**
 * Provides methods to interact with the MTN Momo Collections API.
 */
export class Controller {
  constructor(options: ControllerOptions);

  /**
   * Generates a new UUID v4.
   */
  generateUUID(): Promise<string>;

  /**
   * Initiates a request to pay.
   */
  requestToPay(
    amount: string | number,
    currency: string,
    externalId: string,
    partyIdType: string,
    partyId: string,
    payerMessage: string,
    payeeNote: string
  ): Promise<RequestToPayResponse>;

  /**
   * Retrieves the transaction status for a given reference ID.
   */
  getTransactionStatus(referenceId: string): Promise<Record<string, unknown>>;
}

/**
 * Initiates a request to pay using the MTN Momo Collections API and
 * returns the response along with the transaction status.
 */
export function makeRequest(options: MakeRequestOptions): Promise<MakeRequestResult>;
