import {
  Controller,
  ControllerOptions,
  PartyIdType,
  RequestToPayFailure,
  RequestToPayResponse,
  RequestToPayTransactionStatus,
} from './momo.js';


/**
 * Options for the stateless {@link requestToPay} helper. Combines the
 * {@link ControllerOptions} (credentials) with the request-to-pay fields.
 */
export interface RequestToPayOptions extends ControllerOptions {
  /** The amount to be paid. */
  amount: string | number;
  /** The party ID of the payer. */
  partyId: string;
  /** The type of the party ID. Defaults to `'MSISDN'`. */
  partyIdType?: PartyIdType;
  /** An ID generated by your system to uniquely identify the transaction. */
  externalId?: string;
  /** A message that will be displayed to the payer. */
  payerMessage?: string;
  /** A note that will be displayed to the payee. */
  payeeNote?: string;
}

/**
 * Options for the stateless {@link getRequestToPayTransactionStatus} helper.
 */
export interface GetRequestToPayTransactionStatusOptions extends ControllerOptions {
  /** The reference ID of the transaction. */
  referenceId: string;
}

/**
 * Options for the stateless {@link requestToPayAndWait} helper.
 */
export interface RequestToPayAndWaitOptions extends RequestToPayOptions {
  /** Maximum polling duration in milliseconds. Defaults to `60_000`. */
  maxDurationMs?: number;
  /** Initial backoff delay in milliseconds. Defaults to `1_000`. */
  initialDelayMs?: number;
  /** Backoff multiplier applied after each poll. Defaults to `2`. */
  backoffMultiplier?: number;
}

/**
 * Stateless version of {@link Controller.requestToPay}. Creates a

 * {@link Controller} internally from the provided options.
 */
export async function requestToPay(options: RequestToPayOptions): Promise<RequestToPayResponse> {
  const { amount, partyId, partyIdType, externalId, payerMessage, payeeNote, ...controllerOptions } = options;
  const app = new Controller(controllerOptions);
  return app.requestToPay({ amount, partyId, partyIdType, externalId, payerMessage, payeeNote });
}

/**
 * Stateless version of {@link Controller.getRequestToPayTransactionStatus}.
 * Creates a {@link Controller} internally from the provided options.
 */
export async function getRequestToPayTransactionStatus(
  options: GetRequestToPayTransactionStatusOptions
): Promise<RequestToPayTransactionStatus> {
  const { referenceId, ...controllerOptions } = options;
  const app = new Controller(controllerOptions);
  return app.getRequestToPayTransactionStatus({ referenceId });
}


/**
 * Stateless version of {@link Controller.requestToPayAndWait}.
 * Creates a {@link Controller} internally from the provided options.
 */
export async function requestToPayAndWait(
  options: RequestToPayAndWaitOptions
): Promise<RequestToPayTransactionStatus | RequestToPayFailure | 'timeout'> {
  const { callbackHost, userApiKey, userId, primaryKey, targetEnvironment, currency, ...requestOptions } = options;
  const app = new Controller({ callbackHost, userApiKey, userId, primaryKey, targetEnvironment, currency });
  return app.requestToPayAndWait(requestOptions);
}
