import { Controller, ControllerOptions, RequestToPayResponse } from './momo.js';

/**
 * Options for the {@link makeRequest} function.
 */
export interface MakeRequestOptions extends ControllerOptions {
  /** The amount to be paid. */
  amount: string | number;
  /** An ID generated by your system to uniquely identify the transaction. */
  externalId: string;
  /** The type of the party ID (e.g., MSISDN, EMAIL, etc.). */
  partyIdType: 'MSISDN' | 'EMAIL' | 'PARTY_CODE';
  /** The party ID of the payer. */
  partyId: string;
  /** A message that will be displayed to the payer. */
  payerMessage?: string;
  /** A note that will be displayed to the payee. */
  payeeNote?: string;
}

/**
 * The resolved value of {@link makeRequest}.
 */
export interface MakeRequestResult {
  /** The response from the API. */
  response: RequestToPayResponse;
  /** The transaction status. */
  status: Record<string, unknown>;
}

/**
 * Initiates a request to pay using the MTN Momo Collections API and
 * returns the response along with the transaction status.
 */
export async function makeRequest({
  callbackHost,
  userApiKey,
  userId,
  primaryKey,
  targetEnvironment,
  currency,
  amount,
  externalId,
  partyIdType,
  partyId,
  payerMessage,
  payeeNote,
}: MakeRequestOptions): Promise<MakeRequestResult> {
  const app = new Controller({
    callbackHost,
    userApiKey,
    userId,
    primaryKey,
    targetEnvironment,
    currency,
  });

  try {
    const response = await app.requestToPay(
      amount,
      partyIdType,
      partyId,
      payerMessage,
      payeeNote,
      externalId
    );

    const status = await app.getTransactionStatus(response.referenceId);

    return { response, status };
  } catch (error) {
    console.error('Error:', error);
    throw error;
  }
}
